name = "ArrayAllez"
uuid = "42ed035d-9ad9-5097-b4a3-321d9b0dde85"
license = "MIT"
version = "0.0.6"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
FillArrays = "0.6, 0.7, 0.8"
LRUCache = "0.3, 1"
MacroTools = "0.4, 0.5"
NNlib = "0.6.5, 0.7"
NamedDims = "0.2"
Requires = "0.5, 1"
ZygoteRules = "0.1, 0.2"
julia = "1"

[extras]
AppleAccelerate = "13e28ba4-7ad8-5781-acae-3021b1ed3924"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IntelVectorMath = "c8ce9da6-5d36-5c03-b118-5a70151be7bc"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Yeppp = "6310b701-1812-5374-a82f-9f6f2d54a40a"

[targets]
test = ["Test", "AppleAccelerate", "OMEinsum", "Tracker", "ForwardDiff", "Yeppp"]
